<?php 
$gpath = $_SERVER['DOCUMENT_ROOT'];
if($gpath[0]=='/')
define('S','/');
else
define('S','\\');
define('GPATH',$gpath.S);

require_once(GPATH.'sendmail'.S.'mail.php');

ob_start();
$mail = new PHPMailer();
$mail->isSMTP();
$mail->SMTPDebug  = 1;
$mail->Host = 'mocha3036.mochahost.com';
$mail->SMTPAuth = true;
$mail->Username = 'gpspg@gemad.net'; //paste one generated by Mailtrap
$mail->Password = 'S@V~T80!bt71'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 2525;
$mail->AuthType = 'PLAIN';
exit();

$mail->setFrom('gpspg@gemad.net', 'GPS-PG');
$mail->addReplyTo('gpspg@gemad.net', 'GPS-PG');
$mail->addAddress($to_email, $to_nome);
//$mail->addCC('cc1@example.com', 'Elena');
//$mail->addBCC('bcc1@example.com', 'Alex');
$mail->Subject = $titulo;

//$mail->addAttachment('path/to/invoice1.pdf', 'invoice1.pdf');
//$mysql_data = $mysql_row['blob_data'];
//$mail->addStringAttachment($mysql_data, 'db_data.db'); 
//$mail->addStringAttachment(file_get_contents($url), 'myfile.pdf');

$mail->isHTML(true);

$mail->addEmbeddedImage(GPATH.'images/logosmall.png.jpg', 'logo');
$mail->CharSet="UTF-8";
$mail->Body = '<img src="cid:logo">';

/*ob_start();
include 'modelo/'.$modelo.'.php';
$mailContent = ob_get_contents();
ob_end_clean();*/
$mail->Body = $mailContent;

//$mail->msgHTML(file_get_contents('contents.html'), __DIR__);

if($mail->send()){
    $resposta = 'OK';
}else{
    $resposta = 'NOK';
}
$result = ob_get_contents();
ob_end_clean();

